function [A,B,C] = GlobalLinearBodyDynamicsAuto(in1)
%GLOBALLINEARBODYDYNAMICSAUTO
%    [A,B,C] = GLOBALLINEARBODYDYNAMICSAUTO(IN1)

%    This function was generated by the Symbolic Math Toolbox version 8.2.
%    27-Oct-2023 13:29:42

r1_1 = in1(1);
r1_2 = in1(4);
r3_1 = in1(3);
r3_2 = in1(6);
A = reshape([0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0],[6,6]);
if nargout > 1
    B = reshape([0.0,0.0,0.0,2.095557418273261e-2,0.0,r3_1.*(1.0e1./2.1e1),0.0,0.0,0.0,0.0,2.095557418273261e-2,r1_1.*(-1.0e1./2.1e1),0.0,0.0,0.0,2.095557418273261e-2,0.0,r3_2.*(1.0e1./2.1e1),0.0,0.0,0.0,0.0,2.095557418273261e-2,r1_2.*(-1.0e1./2.1e1)],[6,4]);
end
if nargout > 2
    C = [0.0;0.0;0.0;0.0;-9.81e2./1.0e2;0.0];
end
