function j = GlobalKinematicsAuto(in1)
%GLOBALKINEMATICSAUTO
%    J = GLOBALKINEMATICSAUTO(IN1)

%    This function was generated by the Symbolic Math Toolbox version 8.2.
%    27-Oct-2023 13:29:46

q1 = in1(1,:);
q2 = in1(2,:);
q3 = in1(3,:);
q4 = in1(4,:);
q6 = in1(6,:);
t2 = cos(q3);
t3 = t2.*(3.0./1.0e1);
t4 = sin(q3);
t5 = sin(q4);
t6 = cos(q4);
t7 = t4.*(3.0./1.0e1);
t8 = sin(q6);
t9 = cos(q6);
j = reshape([q1-t2.*(3.0./1.0e1),0.0,q2-t4.*(3.0./1.0e1),q1-t2.*(3.0./1.0e1)+t2.*t6.*(1.7e1./5.0e1)-t4.*t5.*(1.7e1./5.0e1),0.0,q2-t4.*(3.0./1.0e1)+t2.*t5.*(1.7e1./5.0e1)+t4.*t6.*(1.7e1./5.0e1),q1+t3,0.0,q2+t7,q1+t3+t2.*t9.*(1.7e1./5.0e1)-t4.*t8.*(1.7e1./5.0e1),0.0,q2+t7+t2.*t8.*(1.7e1./5.0e1)+t4.*t9.*(1.7e1./5.0e1)],[3,4]);
