function e = GlobalEEKinematicsAuto(in1)
%GLOBALEEKINEMATICSAUTO
%    E = GLOBALEEKINEMATICSAUTO(IN1)

%    This function was generated by the Symbolic Math Toolbox version 8.2.
%    27-Oct-2023 13:29:46

q1 = in1(1,:);
q2 = in1(2,:);
q3 = in1(3,:);
q4 = in1(4,:);
q5 = in1(5,:);
q6 = in1(6,:);
q7 = in1(7,:);
t2 = cos(q3);
t3 = cos(q4);
t4 = sin(q3);
t5 = sin(q4);
t6 = cos(q6);
t7 = sin(q6);
t8 = cos(q5);
t9 = t2.*t5;
t10 = t3.*t4;
t11 = t9+t10;
t12 = sin(q5);
t13 = t2.*t3;
t14 = t13-t4.*t5;
t15 = cos(q7);
t16 = t2.*t7;
t17 = t4.*t6;
t18 = t16+t17;
t19 = sin(q7);
t20 = t2.*t6;
t21 = t20-t4.*t7;
e = reshape([q1-t2.*(3.0./1.0e1)+t2.*t3.*(1.7e1./5.0e1)-t4.*t5.*(1.7e1./5.0e1)+t8.*t14.*(1.7e1./5.0e1)-t11.*t12.*(1.7e1./5.0e1),0.0,q2-t4.*(3.0./1.0e1)+t2.*t5.*(1.7e1./5.0e1)+t3.*t4.*(1.7e1./5.0e1)+t8.*t11.*(1.7e1./5.0e1)+t12.*t14.*(1.7e1./5.0e1),q1+t2.*(3.0./1.0e1)+t2.*t6.*(1.7e1./5.0e1)-t4.*t7.*(1.7e1./5.0e1)+t15.*t21.*(1.7e1./5.0e1)-t18.*t19.*(1.7e1./5.0e1),0.0,q2+t4.*(3.0./1.0e1)+t2.*t7.*(1.7e1./5.0e1)+t4.*t6.*(1.7e1./5.0e1)+t15.*t18.*(1.7e1./5.0e1)+t19.*t21.*(1.7e1./5.0e1)],[3,2]);
