function out1 = GlobalBodyKinematicsAuto(in1)
%GLOBALBODYKINEMATICSAUTO
%    OUT1 = GLOBALBODYKINEMATICSAUTO(IN1)

%    This function was generated by the Symbolic Math Toolbox version 8.2.
%    27-Oct-2023 13:29:45

q1 = in1(1,:);
q2 = in1(2,:);
q3 = in1(3,:);
t2 = cos(q3);
t3 = sin(q3);
out1 = reshape([q1-t2.*(3.0./1.0e1),0.0,q2-t3.*(3.0./1.0e1),q1+t2.*(3.0./1.0e1),0.0,q2+t3.*(3.0./1.0e1)],[3,2]);
