function J_ee = LocalEEJacobianAuto(in1)
%LOCALEEJACOBIANAUTO
%    J_EE = LOCALEEJACOBIANAUTO(IN1)

%    This function was generated by the Symbolic Math Toolbox version 8.2.
%    27-Oct-2023 13:29:45

q1 = in1(1,:);
q2 = in1(2,:);
t2 = sin(q1);
t3 = cos(q1);
t4 = sin(q2);
t5 = cos(q2);
t6 = t3.*t5.*(1.7e1./5.0e1);
J_ee = reshape([t2.*(-1.7e1./5.0e1)-t2.*t5.*(1.7e1./5.0e1)-t3.*t4.*(1.7e1./5.0e1),t3.*(1.7e1./5.0e1)+t6-t2.*t4.*(1.7e1./5.0e1),t2.*t5.*(-1.7e1./5.0e1)-t3.*t4.*(1.7e1./5.0e1),t6-t2.*t4.*(1.7e1./5.0e1)],[2,2]);
