function out1 = LocalEEVelocityAuto(in1,in2)
%LOCALEEVELOCITYAUTO
%    OUT1 = LOCALEEVELOCITYAUTO(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 8.2.
%    27-Oct-2023 13:29:43

dq1 = in2(1,:);
dq2 = in2(2,:);
q1 = in1(1,:);
q2 = in1(2,:);
t2 = q1+q2;
t3 = sin(t2);
t4 = cos(t2);
out1 = [dq2.*t3.*(-1.7e1./5.0e1)-dq1.*(t3.*(1.7e1./5.0e1)+sin(q1).*(1.7e1./5.0e1));0.0;dq1.*(t4.*(1.7e1./5.0e1)+cos(q1).*(1.7e1./5.0e1))+dq2.*t4.*(1.7e1./5.0e1)];
